name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs_on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
